// Mocks generated by Mockito 5.4.4 from annotations
// in first_application/test/helpers/helpers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i26;
import 'dart:typed_data' as _i27;

import 'package:dartz/dartz.dart' as _i2;
import 'package:first_application/core/error/failure.dart' as _i10;
import 'package:first_application/features/authentication/data/datasources/auth_local_data_source.dart'
    as _i25;
import 'package:first_application/features/authentication/data/datasources/auth_remote_data_source.dart'
    as _i20;
import 'package:first_application/features/authentication/data/models/user_model.dart'
    as _i6;
import 'package:first_application/features/authentication/domain/entities/user.dart'
    as _i19;
import 'package:first_application/features/authentication/domain/repositories/auth_repository.dart'
    as _i7;
import 'package:first_application/features/authentication/domain/usecases/log_in_usecase.dart'
    as _i22;
import 'package:first_application/features/authentication/domain/usecases/log_out_usecase.dart'
    as _i24;
import 'package:first_application/features/authentication/domain/usecases/sign_up_usecase.dart'
    as _i23;
import 'package:first_application/features/product/data/data_sources/remote_data_source.dart'
    as _i12;
import 'package:first_application/features/product/data/models/product_model.dart'
    as _i3;
import 'package:first_application/features/product/domain/entities/product.dart'
    as _i11;
import 'package:first_application/features/product/domain/repositories/product_repository.dart'
    as _i5;
import 'package:first_application/features/product/domain/usecases/delete_product_usecase.dart'
    as _i16;
import 'package:first_application/features/product/domain/usecases/get_all_products_usecase.dart'
    as _i15;
import 'package:first_application/features/product/domain/usecases/get_product_usecase.dart'
    as _i14;
import 'package:first_application/features/product/domain/usecases/insert_product_usecase.dart'
    as _i18;
import 'package:first_application/features/product/domain/usecases/update_product_usecase.dart'
    as _i17;
import 'package:http/http.dart' as _i8;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i21;
import 'package:shared_preferences/shared_preferences.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductModel_1 extends _i1.SmartFake implements _i3.ProductModel {
  _FakeProductModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_3 extends _i1.SmartFake
    implements _i4.AddressCheckResult {
  _FakeAddressCheckResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_4 extends _i1.SmartFake
    implements _i5.ProductRepository {
  _FakeProductRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_5 extends _i1.SmartFake implements _i6.UserModel {
  _FakeUserModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_6 extends _i1.SmartFake
    implements _i7.UserRepository {
  _FakeUserRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_7 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_8 extends _i1.SmartFake
    implements _i8.StreamedResponse {
  _FakeStreamedResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i5.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>> getProduct(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>.value(
                _FakeEither_0<_i10.Failure, _i11.ProductEntity>(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> insertProduct(
          _i11.ProductEntity? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [product],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #insertProduct,
            [product],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> updateProduct(
    String? id,
    _i11.ProductEntity? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            id,
            product,
          ],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #updateProduct,
            [
              id,
              product,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> deleteProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>
      getAllProduct() => (super.noSuchMethod(
            Invocation.method(
              #getAllProduct,
              [],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i11.ProductEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.ProductEntity>>(
              this,
              Invocation.method(
                #getAllProduct,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i12.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.ProductModel> getProductById(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [
            id,
            token,
          ],
        ),
        returnValue: _i9.Future<_i3.ProductModel>.value(_FakeProductModel_1(
          this,
          Invocation.method(
            #getProductById,
            [
              id,
              token,
            ],
          ),
        )),
      ) as _i9.Future<_i3.ProductModel>);

  @override
  _i9.Future<List<_i3.ProductModel>> getAllProduct(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProduct,
          [token],
        ),
        returnValue:
            _i9.Future<List<_i3.ProductModel>>.value(<_i3.ProductModel>[]),
      ) as _i9.Future<List<_i3.ProductModel>>);

  @override
  _i9.Future<bool> deleteProduct(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [
            id,
            token,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> insertProduct(
    _i11.ProductEntity? product,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [
            product,
            token,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> updateProduct(
    String? id,
    _i11.ProductEntity? productEntity,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            id,
            productEntity,
            token,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i13.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i9.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i4.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i4.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i4.AddressCheckOptions>[],
      ) as List<_i4.AddressCheckOptions>);

  @override
  set addresses(List<_i4.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i4.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i9.Future<_i4.InternetConnectionStatus>.value(
            _i4.InternetConnectionStatus.connected),
      ) as _i9.Future<_i4.InternetConnectionStatus>);

  @override
  _i9.Stream<_i4.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i9.Stream<_i4.InternetConnectionStatus>.empty(),
      ) as _i9.Stream<_i4.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<_i4.AddressCheckResult> isHostReachable(
          _i4.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i9.Future<_i4.AddressCheckResult>.value(_FakeAddressCheckResult_3(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i9.Future<_i4.AddressCheckResult>);
}

/// A class which mocks [GetProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductUseCase extends _i1.Mock implements _i14.GetProductUseCase {
  MockGetProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>> execute(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>.value(
                _FakeEither_0<_i10.Failure, _i11.ProductEntity>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i11.ProductEntity>>);
}

/// A class which mocks [GetAllProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProductUseCase extends _i1.Mock
    implements _i15.GetAllProductUseCase {
  MockGetAllProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i9
            .Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i11.ProductEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.ProductEntity>>>);
}

/// A class which mocks [DeleteProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductUseCase extends _i1.Mock
    implements _i16.DeleteProductUseCase {
  MockDeleteProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> execute(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [UpdateProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductUseCase extends _i1.Mock
    implements _i17.UpdateProductUseCase {
  MockUpdateProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> execute(
    String? id,
    _i11.ProductEntity? productEntity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            id,
            productEntity,
          ],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [
              id,
              productEntity,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [InsertProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertProductUseCase extends _i1.Mock
    implements _i18.InsertProductUseCase {
  MockInsertProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> execute(
          _i11.ProductEntity? productEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [productEntity],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [productEntity],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> userLogIn(
    _i19.UserEntity? userEntity,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userLogIn,
          [
            userEntity,
            password,
          ],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #userLogIn,
            [
              userEntity,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i19.UserEntity>> userSignUp(
    _i19.UserEntity? userEntity,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userSignUp,
          [
            userEntity,
            password,
          ],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i19.UserEntity>>.value(
                _FakeEither_0<_i10.Failure, _i19.UserEntity>(
          this,
          Invocation.method(
            #userSignUp,
            [
              userEntity,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i19.UserEntity>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> userLogOut() =>
      (super.noSuchMethod(
        Invocation.method(
          #userLogOut,
          [],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #userLogOut,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i20.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> loginUser(
    _i19.UserEntity? userEntity,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            userEntity,
            password,
          ],
        ),
        returnValue: _i9.Future<String>.value(_i21.dummyValue<String>(
          this,
          Invocation.method(
            #loginUser,
            [
              userEntity,
              password,
            ],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i6.UserModel> registerUser(
    _i19.UserEntity? userEntity,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [
            userEntity,
            password,
          ],
        ),
        returnValue: _i9.Future<_i6.UserModel>.value(_FakeUserModel_5(
          this,
          Invocation.method(
            #registerUser,
            [
              userEntity,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i6.UserModel>);

  @override
  _i9.Future<_i6.UserModel> getUser(String? token) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [token],
        ),
        returnValue: _i9.Future<_i6.UserModel>.value(_FakeUserModel_5(
          this,
          Invocation.method(
            #getUser,
            [token],
          ),
        )),
      ) as _i9.Future<_i6.UserModel>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i22.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_6(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i7.UserRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> execute(
    _i19.UserEntity? userEntity,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            userEntity,
            password,
          ],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [
              userEntity,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);
}

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i23.SignUpUseCase {
  MockSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_6(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i7.UserRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i19.UserEntity>> execute(
    _i19.UserEntity? userEntity,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            userEntity,
            password,
          ],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i19.UserEntity>>.value(
                _FakeEither_0<_i10.Failure, _i19.UserEntity>(
          this,
          Invocation.method(
            #execute,
            [
              userEntity,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i19.UserEntity>>);
}

/// A class which mocks [LogOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogOutUseCase extends _i1.Mock implements _i24.LogOutUseCase {
  MockLogOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_6(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i7.UserRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, bool>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, bool>>.value(
            _FakeEither_0<_i10.Failure, bool>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, bool>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i25.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> cacheToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [token],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<String?> getCachedToken() => (super.noSuchMethod(
        Invocation.method(
          #getCachedToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<void> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> cacheLoginStatus(bool? isLoggedIn) => (super.noSuchMethod(
        Invocation.method(
          #cacheLoginStatus,
          [isLoggedIn],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> getLoginStatus() => (super.noSuchMethod(
        Invocation.method(
          #getLoginStatus,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i8.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i8.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i8.Response>);

  @override
  _i9.Future<_i8.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i8.Response>);

  @override
  _i9.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i8.Response>);

  @override
  _i9.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i8.Response>);

  @override
  _i9.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i8.Response>);

  @override
  _i9.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i26.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i8.Response>.value(_FakeResponse_7(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i8.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i21.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i27.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i27.Uint8List>.value(_i27.Uint8List(0)),
      ) as _i9.Future<_i27.Uint8List>);

  @override
  _i9.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i8.StreamedResponse>.value(_FakeStreamedResponse_8(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i8.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
